In [92]:
# Basic Importations 
import pandas as pd 
import numpy as np
import os

# Importations 
from sklearn.model_selection import train_test_split, GridSearchCV, cross_validate
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn import datasets
from sklearn.svm import SVC
from sklearn.metrics import precision_score, recall_score, confusion_matrix, roc_auc_score, classification_report

In [94]:
df = pd.read_csv('data2.csv',delimiter=',')
print(len(df))

960


In [95]:
df

MO  EL-lab  El-modarag  Hew  WE_99EDC6  medhat     location
0   -100    -100         -63  -62       -100    -100  modarag_cor
1   -100    -100         -64  -63       -100    -100  modarag_cor
2   -100    -100         -79  -61       -100     -85  modarag_cor
3   -100    -100         -68  -65       -100     -86  modarag_cor
4   -100    -100         -71  -51       -100     -88  modarag_cor
..   ...     ...         ...  ...        ...     ...          ...
955 -100    -100        -100  -86       -100    -100      modarag
956 -100    -100        -100  -78       -100    -100      modarag
957 -100    -100         -52  -90       -100    -100      modarag
958  -89    -100         -57  -87       -100    -100      modarag
959  -90    -100        -100  -76       -100    -100      modarag

[960 rows x 7 columns]

In [96]:
X = df.iloc[:, 0:-1].values
y = df.iloc[:, -1].values

In [97]:
print(X,y)
print(len(X),len(y))

[[-100 -100  -63  -62 -100 -100]
 [-100 -100  -64  -63 -100 -100]
 [-100 -100  -79  -61 -100  -85]
 ...
 [-100 -100  -52  -90 -100 -100]
 [ -89 -100  -57  -87 -100 -100]
 [ -90 -100 -100  -76 -100 -100]] ['modarag_cor' 'modarag_cor' 'modarag_cor' 'modarag_cor' 'modarag_cor'
 'modarag_cor' 'modarag_cor' 'modarag_cor' 'modarag_cor' 'modarag_cor'
 'modarag_cor' 'modarag_cor' 'modarag_cor' 'modarag_cor' 'modarag_cor'
 'modarag_cor' 'modarag_cor' 'modarag_cor' 'modarag_cor' 'modarag_cor'
 'modarag_cor' 'modarag_cor' 'modarag_cor' 'modarag_cor' 'modarag_cor'
 'modarag_cor' 'modarag_cor' 'modarag_cor' 'modarag_cor' 'modarag_cor'
 'modarag_cor' 'modarag_cor' 'modarag_cor' 'modarag_cor' 'modarag_cor'
 'modarag_cor' 'modarag_cor' 'modarag_cor' 'modarag_cor' 'modarag_cor'
 'modarag_cor' 'modarag_cor' 'modarag_cor' 'modarag_cor' 'modarag_cor'
 'modarag_cor' 'modarag_cor' 'modarag_cor' 'modarag_cor' 'modarag_cor'
 'modarag_cor' 'modarag_cor' 'modarag_cor' 'modarag_cor' 'modarag_cor'
 'modarag_cor' 

In [98]:
print((X.shape),(y.shape))

(960, 6) (960,)


In [99]:
print(X[0])

[-100 -100  -63  -62 -100 -100]


In [100]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [101]:
print(len(X_train), len(y_train))
print(len(X_test), len(y_test))

768 768
192 192


In [102]:
# Check Balancing 
pd.Series(y_train).value_counts()

lab_2           103
cor_1           101
cor_3           101
modarag_cor      98
cor_2            93
lab_1            92
modarag          91
doctors_room     89
dtype: int64

In [103]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(768, 6)
(768,)
(192, 6)
(192,)


In [104]:
classifiers = {
    'knn': KNeighborsClassifier(5),
    'NB': GaussianNB(),
    'tree': DecisionTreeClassifier(max_depth=10),
    'forest': RandomForestClassifier(n_estimators=10, max_depth=10),
    'SV': SVC(probability=True, gamma=0.001),
    'LR': LogisticRegression(solver='newton-cg', max_iter=400)
}

In [105]:
# Metrics 
metrics = ['accuracy', 'f1_weighted', 'roc_auc_ovr_weighted', 'precision_weighted', 'recall_weighted']
# metrics = ['accuracy', 'f1_weighted']

# Cross Validate the models 
scores = {}
for name, clf in classifiers.items():
    print(f'Training {name} model .. ')
    res = cross_validate(clf, X_train, y_train, cv=11, scoring=metrics, return_estimator=True)
#     print(res)
    
    score = {"test_f1_weighted": np.mean(res['test_f1_weighted']), 
             'test_roc_auc_ovr_weighted': np.mean(res['test_roc_auc_ovr_weighted']), 
             'test_precision_weighted': np.mean(res['test_precision_weighted']),
             'test_recall_weighted': np.mean(res['test_recall_weighted']),
             'test_accuracy': np.mean(res['test_accuracy']),
             'estimator': res['estimator'][0]
            }
    
    print("test_f1_weighted", score['test_f1_weighted'])
    print('test_roc_auc_ovr', score['test_roc_auc_ovr_weighted'])
    print('test_precicison', score['test_precision_weighted'])
    print('test_recall', score['test_recall_weighted'])
    print('accuracy', score['test_accuracy'])
    print('\n')
    
    # Add each model`s scores to scores
    scores[name] = score

Training knn model .. 
test_f1_weighted 0.8622526447449487
test_roc_auc_ovr 0.9749437128753894
test_precicison 0.8688682899905373
test_recall 0.8646903820816866
accuracy 0.8646903820816866


Training NB model .. 


c:\users\mariam\appdata\local\programs\python\python39\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\users\mariam\appdata\local\programs\python\python39\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\users\mariam\appdata\local\programs\python\python39\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\u

test_f1_weighted 0.6328506377141996
test_roc_auc_ovr 0.9564641993799228
test_precicison 0.717158332660413
test_recall 0.6718991153773763
accuracy 0.6718991153773763


Training tree model .. 
test_f1_weighted 0.8677560052941051
test_roc_auc_ovr 0.953766201257627
test_precicison 0.8818822311072453
test_recall 0.8685676642198381
accuracy 0.8685676642198381


Training forest model .. 
test_f1_weighted 0.8852262703134113
test_roc_auc_ovr 0.9900304297809732
test_precicison 0.8938988687661755
test_recall 0.8854884246188593
accuracy 0.8854884246188593


Training SV model .. 
test_f1_weighted 0.8828809139180909
test_roc_auc_ovr 0.9908163504162082
test_precicison 0.8923048379668933
test_recall 0.8854884246188593
accuracy 0.8854884246188593


Training LR model .. 
test_f1_weighted 0.7852031959259907
test_roc_auc_ovr 0.9774567244354393
test_precicison 0.7984269980599737
test_recall 0.7865424430641823
accuracy 0.7865424430641823




In [106]:
model = RandomForestClassifier(n_estimators=200, random_state=0)
# model = DecisionTreeClassifier(max_depth=10)
# model =SVC(probability=True, gamma=0.001)
history = model.fit(X_train, y_train)
# print(history)

In [107]:
    y_pred = model.predict([X_test[0]])
    print("prediction =     ", y_pred)
#     print(list(y_test.values))

    print(model.score(X_test, y_test))

prediction =      ['modarag']
0.8854166666666666


In [108]:
print(model.predict(X_test[0].reshape(1, -1)))

['modarag']


In [88]:
print(X_test[0])

[-100 -100  -60  -86 -100 -100]


In [89]:
import pickle
# save the model to disk
filename = 'finalized_model_99.joblib'
pickle.dump(model, open(filename, 'wb'))

In [75]:
with open('testing-arrays.npy', 'wb') as f:
    np.save(f, X_test)
    np.save(f, y_test)

In [37]:
with open('testing-arrays.npy', 'rb') as f:
    X_test = np.load(f)
    X_test = np.load(f)

print(type(X_test))
print(X_test.shape)
print(X_test.dtype)

print('-'*60)

print(type(y_test))
print(y_test.shape)
print(y_test.dtype)

<class 'numpy.ndarray'>
(54,)
int64
------------------------------------------------------------
<class 'numpy.ndarray'>
(54,)
int64
